# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# ---- 1、基本配置

title: Atrayee's corner of the world

header-img: img/img2.jpg 
description: "Your feature, your way. 
baseurl: "" # 可忽略，官方解释：for example, '/blog' if your blog hosted on 'host/blog'

# ---- 2. Sidebar settings

sidebar: true # 是否使用侧边栏（头像，简介...），看个人喜好吧，我这里启用
sidebar-about-description: "Live, work, pose!<br>活出彩，浪起来，秀出姿态！" # 你的简介，如果上面设置false，这里可不填
sidebar-avatar: /img/blog1.jpg # 你的头像图片的地址

# ---- 3. SNS settings

RSS: false  


github_username:    atrayees      # GitHub



# 个性标签（Featured Tags）

featured-tags: true               
featured-condition-size: 0       
# 好友链接部分（Friends）

friends: [
    {
        title: "Hux Blog",              # 要显示的名称
        href: "http://huangxuan.me/"   # 好友的博客链接
    },
    {
        title: "BY Blog",              # 要显示的名称
        href: "https://github.com/qiubaiying"    # 好友的博客链接
    },
    {
        title: "Clean Blog",              # 要显示的名称
        href: "http://blackrockdigital.github.io/startbootstrap-clean-blog-jekyll/"    # 好友的博客链接
    }

    # 可以无限加，注意数组语法，如果再加第3个，则需要在第2个的花括号“}“后面加上英文的逗号","
]

# ---- 4、构建配置

# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty   # 
paginate: 10  # 每页展示多少篇博客文章
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"] # Jekyll框架系统配置，无需关注，不要动
anchorjs: true  # if you want to customize anchor. check out line:181 of `post.html`

# 以下配置，不需要动

# Publish posts or collection documents with a future date.
future: true

# Gems # The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM   # use Github Flavored Markdown !important
  # syntax_highlighter_opts:
  #   span:
  #     line_numbers: false
  #   block:
  #     line_numbers: true
  #     start_line: 1

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# ---- 5、插件配置（不怕折腾的小白可以试试） 

# 评论系统：Gitalk(https://github.com/gitalk/gitalk)
gitalk:
  enable: true #是否开启Gitalk评论
  clientID: 73b05209d243dc91289d #生成的clientID
  clientSecret: 048bc73b2f47a2ed0681a6543d88669313e6c052 #生成的clientSecret
  repo: meswx.github.io #仓库名称
  owner: meswx #github用户名
  admin: meswx
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

# Google Analytics
ga_track_id: 'UA-145463114-1' # 你用Google账号去注册一个就会给你一个这样的id，Format: UA-xxxxxx-xx
ga_domain: auto     # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

